### PR TITLE
Add multiarch builds

### PR DESCRIPTION
**Pull request by jmreicha**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] (NA)Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jmreicha** [comment]
@conda-forge-admin please rerender

**Comment by jmreicha** [comment]
@isuruf What did I do wrong? 🤔

**Comment by isuruf** [comment]
Ignore "Travis CI - Pull Request" and only look at "continuous-integration/travis-ci/pr"

**Comment by jmreicha** [comment]
@chrisburr Can you take a look at this?

**Comment by chrisburr** [comment]
I completely missed this, thanks :)

**Pull request merged**
